{
  "formatVersion": "1.1",
  "component": {
    "url": "../../skyprint-template/0.1.3/skyprint-template-0.1.3.module",
    "group": "com.dcorp.skyprint",
    "module": "skyprint-template",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.dcorp.skyprint",
          "module": "skyprint-core",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "skyprint-template.aar",
          "url": "skyprint-template-android-0.1.3.aar",
          "size": 76168,
          "sha512": "d34c9730c1bcc609bf1be65c21417c67b0da3aa8daa1779bf79efd531ed0a4dcd78a5cd839170d50e4d88ba9d649eb84d3ce332987d177e2e04ad990598fead5",
          "sha256": "c178e1554fdc54b6f05a99f9e03174aa2b493493e7ee38e287eb46d408806044",
          "sha1": "511661a29c5bc06d2826e5681b3c47ccf451ebc7",
          "md5": "7c628937efcb8aa63732b81ff785d3c4"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.dcorp.skyprint",
          "module": "skyprint-core",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "skyprint-template.aar",
          "url": "skyprint-template-android-0.1.3.aar",
          "size": 76168,
          "sha512": "d34c9730c1bcc609bf1be65c21417c67b0da3aa8daa1779bf79efd531ed0a4dcd78a5cd839170d50e4d88ba9d649eb84d3ce332987d177e2e04ad990598fead5",
          "sha256": "c178e1554fdc54b6f05a99f9e03174aa2b493493e7ee38e287eb46d408806044",
          "sha1": "511661a29c5bc06d2826e5681b3c47ccf451ebc7",
          "md5": "7c628937efcb8aa63732b81ff785d3c4"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "skyprint-template-android-0.1.3-sources.jar",
          "url": "skyprint-template-android-0.1.3-sources.jar",
          "size": 15644,
          "sha512": "c736ee6a2058b85dd6b216bd3b82238b0b5a755803272664050d95cddf3cc88a4421130cad7d9d24fbb5823af42fac2d423afebbdd04754b8ae49eaa09eb5b6e",
          "sha256": "38dfd855c003eeae7e0fa1061a8b925f624966b477b1f3a2a16147afa4851a8d",
          "sha1": "d203115551e4c0ee8f9eb2d8250ceea33d19168a",
          "md5": "804c9ecbf20ac0b88aaf3743ac88ce77"
        }
      ]
    }
  ]
}
