{
  "formatVersion": "1.1",
  "component": {
    "url": "../../skyprint-core/0.1.0/skyprint-core-0.1.0.module",
    "group": "com.dcorp.skyprint",
    "module": "skyprint-core",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "skyprint-core.aar",
          "url": "skyprint-core-android-0.1.0.aar",
          "size": 232600,
          "sha512": "9da270c76b6a975a6c179dd495707fc1a663dbdb902a8c598ab3da3596b5dcc433a577aa840288939e03aec1df1d3a29b6366526fb7a46e1d13b7901b600579f",
          "sha256": "75b6bbe362ea324b1362043ca110c8097c5c5566165146e5d2edcea378349d53",
          "sha1": "f73138685c389f1d5e5a3d6e5adaea28737db8f0",
          "md5": "353cf809ea868c86a287898a2b4f3c13"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.juul.kable",
          "module": "kable-core",
          "version": {
            "requires": "0.45.0"
          }
        }
      ],
      "files": [
        {
          "name": "skyprint-core.aar",
          "url": "skyprint-core-android-0.1.0.aar",
          "size": 232600,
          "sha512": "9da270c76b6a975a6c179dd495707fc1a663dbdb902a8c598ab3da3596b5dcc433a577aa840288939e03aec1df1d3a29b6366526fb7a46e1d13b7901b600579f",
          "sha256": "75b6bbe362ea324b1362043ca110c8097c5c5566165146e5d2edcea378349d53",
          "sha1": "f73138685c389f1d5e5a3d6e5adaea28737db8f0",
          "md5": "353cf809ea868c86a287898a2b4f3c13"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "skyprint-core-android-0.1.0-sources.jar",
          "url": "skyprint-core-android-0.1.0-sources.jar",
          "size": 48944,
          "sha512": "662ba7aa8c9a17cb1bebc4d551b906904a7176a19223637ed20496c87fe3cce0300dd2d1264c10537479c0b61797c1d504c13856835b8c5b86046d2e8bc9e1bd",
          "sha256": "309e87586dcb5716cfff7cf8a3171ef7b89157efe2e894ba7b623bb15eb911ae",
          "sha1": "a669a77cbc3409af9271f1222a8ebef17af84e68",
          "md5": "18ebd92410ef2685f8f4b98bb50d4f9f"
        }
      ]
    }
  ]
}
