{
  "formatVersion": "1.1",
  "component": {
    "url": "../../skyprint-template/0.1.0/skyprint-template-0.1.0.module",
    "group": "com.dcorp.skyprint",
    "module": "skyprint-template",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.dcorp.skyprint",
          "module": "skyprint-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "skyprint-template.aar",
          "url": "skyprint-template-android-0.1.0.aar",
          "size": 76157,
          "sha512": "8871514e7941c9631bb4a11f56bb3822bb601f09f44cafd73c2fc92fe308912649d34e1e9b895f55f2fc6db80d12928d08e18cbdc729eefe4081a4f9e48730f7",
          "sha256": "af751aa30b41a35ab88ccff454c7852d893e9a2da21c762f51ab932fcce9f0c4",
          "sha1": "45bdc69f65664a72bae1ff2f319b28022314148e",
          "md5": "6aba0748980fb4dfcef31956ddbad397"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.dcorp.skyprint",
          "module": "skyprint-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "skyprint-template.aar",
          "url": "skyprint-template-android-0.1.0.aar",
          "size": 76157,
          "sha512": "8871514e7941c9631bb4a11f56bb3822bb601f09f44cafd73c2fc92fe308912649d34e1e9b895f55f2fc6db80d12928d08e18cbdc729eefe4081a4f9e48730f7",
          "sha256": "af751aa30b41a35ab88ccff454c7852d893e9a2da21c762f51ab932fcce9f0c4",
          "sha1": "45bdc69f65664a72bae1ff2f319b28022314148e",
          "md5": "6aba0748980fb4dfcef31956ddbad397"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "skyprint-template-android-0.1.0-sources.jar",
          "url": "skyprint-template-android-0.1.0-sources.jar",
          "size": 15540,
          "sha512": "17a17f804401aebce7114ca54f93e44f33b32af8259391820819381d39cb4c3179001d3a83eecc59ee534061c942efdb18304758e2f8fe8e669f1e6aa1333e05",
          "sha256": "aab07413d7e35c9d6f63f20c0d514043429a18cd10643c5d2ab6de19d0ce7fe6",
          "sha1": "b976b36c19751597a15d91862c953f9be9e20660",
          "md5": "bb3d477bd5f47c6463f79c853499d128"
        }
      ]
    }
  ]
}
