#!/usr/bin/env python3
"""
generate_wbs.py — render docs/wbs.md from traceability.json.

This is a VIEW, never hand-maintained. Re-run after any update_node.py call
that should be reflected in the human-readable WBS.

    python3 generate_wbs.py [--file traceability.json] [--out docs/wbs.md]
"""
import argparse
import os
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _lib import load_graph, now_iso, resolve_graph_path  # noqa: E402

STATUS_MARK = {
    "pass": "✅",
    "done": "✅",
    "fail": "❌",
    "blocked": "⛔",
    "in_progress": "🔶",
    "pending": "⬜",
}


def mark(status):
    return STATUS_MARK.get(status, "⬜")


def children_by_depends_on(nodes, parent_id):
    return sorted(
        nid for nid, n in nodes.items() if parent_id in n.get("depends_on", [])
    )


def trace_line(nodes, node_id):
    node = nodes[node_id]
    parts = []
    for t in node.get("traces_to", []):
        tnode = nodes.get(t)
        if tnode:
            parts.append("%s %s (%s)" % (mark(tnode["status"]), t, tnode["status"]))
        else:
            parts.append("%s (missing)" % t)
    return "; ".join(parts) if parts else "—"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--file", default=None)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    graph_path = resolve_graph_path(args.file)
    project_root = os.path.dirname(os.path.abspath(graph_path))
    data = load_graph(graph_path)
    nodes = data["nodes"]
    out_path = args.out or os.path.join(project_root, "docs", "wbs.md")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    counts = defaultdict(lambda: defaultdict(int))
    for n in nodes.values():
        counts[n["type"]][n["status"]] += 1

    lines = []
    lines.append("# WBS — %s" % data.get("project", ""))
    lines.append("")
    lines.append(
        "> Generated by `generate_wbs.py` at %s — do not hand-edit, re-run the "
        "script instead." % now_iso()
    )
    lines.append("")
    lines.append("## Coverage summary")
    lines.append("")
    lines.append("| Type | Total | " + " | ".join(sorted(STATUS_MARK)) + " |")
    lines.append("|---|---|" + "---|" * len(STATUS_MARK))
    for t in ("REQ", "DESIGN", "CODE", "TEST-UAT", "TEST-SIT", "TEST-UNIT"):
        row_counts = counts.get(t, {})
        total = sum(row_counts.values())
        cells = [str(row_counts.get(s, 0)) for s in sorted(STATUS_MARK)]
        lines.append("| %s | %d | %s |" % (t, total, " | ".join(cells)))
    lines.append("")

    modules = sorted({n.get("module") for n in nodes.values() if n.get("module")})
    if modules:
        lines.append("## Modules")
        lines.append("")
        lines.append(", ".join(modules))
        lines.append("")

    lines.append("## Requirements")
    lines.append("")
    req_ids = sorted(nid for nid, n in nodes.items() if n["type"] == "REQ")
    for req_id in req_ids:
        req = nodes[req_id]
        mod = " `[%s]`" % req["module"] if req.get("module") else ""
        lines.append(
            "### %s %s — %s (%s)%s" % (mark(req["status"]), req_id, req["title"], req["status"], mod)
        )
        if req.get("spec_ref"):
            lines.append("- spec_ref: `%s`" % req["spec_ref"])
        if req.get("note"):
            lines.append("- note: %s" % req["note"])
        lines.append("- UAT: %s" % trace_line(nodes, req_id))
        for design_id in children_by_depends_on(nodes, req_id):
            design = nodes[design_id]
            lines.append(
                "  - %s **%s** — %s (%s)" % (mark(design["status"]), design_id, design["title"], design["status"])
            )
            if design.get("spec_ref"):
                lines.append("    - spec_ref: `%s`" % design["spec_ref"])
            lines.append("    - SIT: %s" % trace_line(nodes, design_id))
            for code_id in children_by_depends_on(nodes, design_id):
                code = nodes[code_id]
                lines.append(
                    "    - %s `%s` — %s (%s)" % (mark(code["status"]), code_id, code["title"], code["status"])
                )
                if code.get("code_ref"):
                    lines.append("      - code_ref: `%s`" % code["code_ref"])
                lines.append("      - Unit: %s" % trace_line(nodes, code_id))
        lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print("OK: wrote %s (%d REQ)" % (out_path, len(req_ids)))


if __name__ == "__main__":
    main()
